const SCHOOLS = [
  {
      "number": 1,
      "name": "深圳实验幼儿园",
      "created_time": "1988年10月",
      "address": "深圳市福田区百花五路32号",
      "street": "园岭街道长城社区",
      "phone": 83340895,
      "organizer": "深圳市教育局",
      "legal_person": "杨梅",
      "principal": "杨梅",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.552043,
      "longitude": 114.090505
  },
  {
      "number": 2,
      "name": "深圳市第二幼儿园",
      "created_time": "1982年01月",
      "address": "深圳市福田区通心岭同心路9号",
      "street": "华强北街道通心岭社区",
      "phone": 88860766,
      "organizer": "深圳市教育局",
      "legal_person": "韩智",
      "principal": "韩智",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.71511,
      "longitude": 114.257109
  },
  {
      "number": 3,
      "name": "深圳市第三幼儿园",
      "created_time": "1983年03月",
      "address": "深圳市福田区梅林一村十三区、十二区",
      "street": "梅林街道梅林一村社区",
      "phone": 83531971,
      "organizer": "深圳市教育局",
      "legal_person": "邱雪华",
      "principal": "邱雪华",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.56752,
      "longitude": 114.0344
  },
  {
      "number": 4,
      "name": "深圳市第四幼儿园",
      "created_time": "1985年09月",
      "address": "深圳市福田区园岭街道园岭二街园1号岭街道红荔社区",
      "street": "园岭街道红荔社区",
      "phone": 22219860,
      "organizer": "深圳市教育局",
      "legal_person": "黎美红",
      "principal": "黎美红",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.715575,
      "longitude": 114.315662
  },
  {
      "number": 5,
      "name": "深圳市第五幼儿园",
      "created_time": "1990年06月",
      "address": "深圳市福田区益田村内中心广场福保街道益田社区",
      "street": "福保街道益田社区",
      "phone": 83813158,
      "organizer": "深圳市教育局",
      "legal_person": "张丹丹",
      "principal": "张丹丹",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.615179,
      "longitude": 114.075363
  },
  {
      "number": 6,
      "name": "深圳市第七幼儿园",
      "created_time": "1994年09月",
      "address": "深圳市福田区华富街道莲花三村内",
      "street": "华富街道莲花三村社区",
      "phone": 83231623,
      "organizer": "深圳市教育局",
      "legal_person": "陈菱",
      "principal": "陈菱",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.546386,
      "longitude": 114.070893
  },
  {
      "number": 7,
      "name": "深圳市第八幼儿园",
      "created_time": "1986年05月",
      "address": "深圳市福田区益田村117栋前",
      "street": "福保街道益田社区",
      "phone": 83457830,
      "organizer": "深圳市教育局",
      "legal_person": "汪秀宏",
      "principal": "汪秀宏",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.508821,
      "longitude": 114.047081
  },
  {
      "number": 8,
      "name": "深圳市第九幼儿园",
      "created_time": "1995年09月",
      "address": "深圳市福田区莲花北村",
      "street": "莲花街道莲花北社区",
      "phone": 83064046,
      "organizer": "深圳市教育局",
      "legal_person": "彭莉",
      "principal": "彭莉",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.558594,
      "longitude": 114.050088
  },
  {
      "number": 9,
      "name": "深圳市第十一幼儿园",
      "created_time": "1994年03月",
      "address": "深圳市福田区福强路1035号",
      "street": "福田街道福民社区",
      "phone": 83393515,
      "organizer": "深圳市教育局",
      "legal_person": "池丽萍",
      "principal": "池丽萍",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.521629,
      "longitude": 114.069843
  },
  {
      "number": 10,
      "name": "深圳市梅林一村幼儿园",
      "created_time": "2000年07月",
      "address": "深圳市福田区梅林一村三区",
      "street": "梅林街道梅林一村社区",
      "phone": 83504107,
      "organizer": "深圳市教育局",
      "legal_person": "姚艺",
      "principal": "姚艺",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.567972,
      "longitude": 114.040237
  },
  {
      "number": 11,
      "name": "深圳市莲花二村幼儿园",
      "created_time": "1992年03月",
      "address": "深圳市福田区红荔路5002号莲花华富街道莲花二村社区",
      "street": "华富街道莲花二村社区",
      "phone": 83222621,
      "organizer": "深圳市教育局",
      "legal_person": "凌春媛",
      "principal": "凌春媛",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.550077,
      "longitude": 114.072032
  },
  {
      "number": 12,
      "name": "深圳市莲花北幼儿园",
      "created_time": "1994年10月",
      "address": "深圳市福田区莲花北村内",
      "street": "莲花街道莲花北社区",
      "phone": 83187190,
      "organizer": "深圳市教育局",
      "legal_person": "史勇萍",
      "principal": "史勇萍",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.559249,
      "longitude": 114.052161
  },
  {
      "number": 13,
      "name": "深圳市彩田幼儿园",
      "created_time": "1993年01月",
      "address": "深圳市福田区莲花街道彩田村内莲花街道彩田社区",
      "street": "莲花街道彩田社区",
      "phone": 83072826,
      "organizer": "深圳市教育局",
      "legal_person": "刘蓓",
      "principal": "刘蓓",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.561578,
      "longitude": 114.060282
  },
  {
      "number": 14,
      "name": "深圳市华富幼儿园",
      "created_time": "1993年09月",
      "address": "深圳市福田区华富街道华富村华华富街道5号黄木岗社区",
      "street": "华富街道黄木岗社区",
      "phone": 83204802,
      "organizer": "深圳市教育局",
      "legal_person": "姜伟平",
      "principal": "姜伟平",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.538365,
      "longitude": 114.066496
  },
  {
      "number": 15,
      "name": "深圳市南华幼儿园",
      "created_time": "1993年03月",
      "address": "深圳市福田区下步庙北区32栋",
      "street": "南园街道锦龙社区",
      "phone": 83621200,
      "organizer": "深圳市教育局",
      "legal_person": "罗艳",
      "principal": "罗艳",
      "class": "省一级",
      "type": "市属公办园",
      "fee": 1008,
      "latitude": 22.537346,
      "longitude": 114.088461
  },
  {
      "number": 16,
      "name": "深圳市福田区第一幼儿园",
      "created_time": "1987年10月",
      "address": "深圳市福田区香蜜湖街道润田路36号",
      "street": "香蜜湖街道农园社区",
      "phone": 82898964,
      "organizer": "深圳市福田教育局",
      "legal_person": "陈玉文",
      "principal": "陈玉文",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.546468,
      "longitude": 114.012955
  },
  {
      "number": 17,
      "name": "深圳市福田区第一幼儿园福安分园",
      "created_time": "2021年08月",
      "address": "深圳市福田区福田街道福安社区新洲路与福华一路交汇处东南角",
      "street": "福田街道福安社区",
      "phone": 88912502,
      "organizer": "深圳市福田区第一幼儿园",
      "legal_person": "莫彦平",
      "principal": "陈玲",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.535706,
      "longitude": 114.051211
  },
  {
      "number": 18,
      "name": "深圳市福田区第二幼儿园",
      "created_time": "1995年09月",
      "address": "深圳市福田区彩田路2046号",
      "street": "福田街道福山社区",
      "phone": 82523067,
      "organizer": "深圳市福田教育局",
      "legal_person": "冯运梅",
      "principal": "冯运梅",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.532998,
      "longitude": 114.0695
  },
  {
      "number": 19,
      "name": "深圳市福田区第二幼儿园爱华分园",
      "created_time": "2021年08月",
      "address": "深圳市福田区南园街道园西社区爱华市场北侧",
      "street": "南园街道南园社区",
      "phone": 82735676,
      "organizer": "深圳市福田区第二幼儿园",
      "legal_person": "刁日霞",
      "principal": "刁日霞",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.539535,
      "longitude": 114.091687
  },
  {
      "number": 20,
      "name": "深圳市福田区第二幼儿园锦龙分园",
      "created_time": "重建中",
      "address": "福田区爱华路锦龙花园",
      "street": "南园街道锦龙社区",
      "phone": 82799887,
      "organizer": "深圳市福田区第二幼儿园",
      "legal_person": "刁日霞",
      "principal": "刁日霞",
      "class": "规范园",
      "type": "区属公办园",
      "latitude": 22.53668,
      "longitude": 114.091669
  },
  {
      "number": 21,
      "name": "深圳市福田区第二幼儿园香蜜湖分园",
      "created_time": "2021年08月",
      "address": "福田区香蜜湖街道香岭社区紫竹六道33号",
      "street": "香蜜湖街道香岭社区",
      "phone": 82737193,
      "organizer": "深圳市福田区第二幼儿园",
      "legal_person": "黄小云",
      "principal": "黄小云",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.534335,
      "longitude": 114.007607
  },
  {
      "number": 22,
      "name": "深圳市福田区第三幼儿园",
      "created_time": "1997年02月",
      "address": "深圳市福田区新洲南路3183号",
      "street": "沙头街道新洲社区",
      "phone": 23939230,
      "organizer": "深圳市福田教育局",
      "legal_person": "黄科",
      "principal": "黄科",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.526104,
      "longitude": 114.049204
  },
  {
      "number": 23,
      "name": "深圳市福田区第三幼儿园翠湾分园",
      "created_time": "2021年08月",
      "address": "深圳市福田区沙头街道翠湾社区福强路4001号深圳文化创意园内",
      "street": "沙头街道翠湾社区",
      "phone": 82519343,
      "organizer": "深圳市福田区第三幼儿园",
      "legal_person": "祁芬",
      "principal": "祁芬",
      "class": "未评级",
      "type": "区属公办园",
      "fee": 840,
      "latitude": 22.518272,
      "longitude": 114.043969
  },
  {
      "number": 24,
      "name": "深圳市福田区第三幼儿园石厦分园",
      "created_time": "2023年7月",
      "address": "福田区石厦北世界4号",
      "street": "福保街道明月社区",
      "phone": 83803447,
      "organizer": "深圳市福田区第三幼儿园",
      "legal_person": "曾代芬",
      "principal": "曾代芳",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.52513,
      "longitude": 114.052474
  },
  {
      "number": 25,
      "name": "深圳市福田区第四幼儿园",
      "created_time": "2019年06月",
      "address": "深圳市福田区园岭街道百花三路8号南天一花园内",
      "street": "园岭街道南天社区",
      "phone": 83217409,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "李林英",
      "principal": "李林英",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.553677,
      "longitude": 114.092967
  },
  {
      "number": 26,
      "name": "深圳市福田区第四幼儿园下梅分园",
      "created_time": "2021年08月",
      "address": "福田区梅林街道梅华支路335号",
      "street": "梅林街道下梅社区",
      "phone": 23987590,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "严梅",
      "principal": "严梅",
      "class": "未评级",
      "type": "区属公办园",
      "fee": 840,
      "latitude": 22.562276,
      "longitude": 114.042537
  },
  {
      "number": 27,
      "name": "深圳市福田区第六幼儿园",
      "created_time": "2019年07月",
      "address": "深圳市福田区沙头街道金地一路155号",
      "street": "沙头街道沙嘴社区",
      "phone": 88602393,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "曹煜",
      "principal": "曹煜",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.519524,
      "longitude": 114.038467
  },
  {
      "number": 28,
      "name": "深圳市福田区第七幼儿园",
      "created_time": "2019年04月",
      "address": "深圳市福田区梅林街道林园东路16号",
      "street": "梅林街道新阁社区",
      "phone": 88377005,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "田晶",
      "principal": "田晶",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.569281,
      "longitude": 114.074825
  },
  {
      "number": 29,
      "name": "深圳市福田区第七幼儿园新新分园",
      "created_time": "2008年02月",
      "address": "福田区石厦街35号新新家园小区内",
      "street": "福保街道新港社区",
      "phone": 23608357,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "邹晓锋",
      "principal": "邹晓锋",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.519452,
      "longitude": 114.052875
  },
  {
      "number": 30,
      "name": "深圳市福田区第八幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区福保街道福田保税区绒花路288号",
      "street": "福保街道福保社区",
      "phone": 83207125,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "吴雪燕",
      "principal": "吴雪燕",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.508821,
      "longitude": 114.047081
  },
  {
      "number": 31,
      "name": "深圳市福田区第九幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区福保街道福保社区菩提路68号金桂大厦裙楼二层、一层西侧",
      "street": "福保街道福保社区",
      "phone": 83215321,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "袁佳",
      "principal": "袁佳",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.514795,
      "longitude": 114.062854
  },
  {
      "number": 32,
      "name": "深圳市福田区第九幼儿园福保分园",
      "created_time": "2023年7月",
      "address": "深圳市福田区菩提路新桂花村四号",
      "street": "福保街道福保社区",
      "phone": 83593048,
      "organizer": "深圳市福田区第九幼儿园",
      "legal_person": "袁佳",
      "principal": "袁佳",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.514902,
      "longitude": 114.063708
  },
  {
      "number": 33,
      "name": "深圳市福田区上沙实验幼儿园",
      "created_time": "2021年08月",
      "address": "广东省深圳市福田区沙头街道上沙银沙路",
      "street": "沙头街道上沙社区",
      "phone": 88606066,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "邓腊梅",
      "principal": "邓腊梅",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.525751,
      "longitude": 114.029141
  },
  {
      "number": 34,
      "name": "深圳市福田区天健天骄幼儿园",
      "created_time": "2021年08月",
      "address": "深圳市福田区莲花街道景田工业园片区更新单元",
      "street": "莲花街道狮岭社区",
      "phone": 82222852,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "罗秀娟",
      "principal": "罗秀娟",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.550754,
      "longitude": 114.040719
  },
  {
      "number": 35,
      "name": "深圳市福田区翠海幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区香蜜湖街道侨香路翠海花园",
      "street": "香蜜湖街道农园社区",
      "phone": 82738273,
      "organizer": "深圳市福田区第一幼儿园",
      "legal_person": "刘彦霞",
      "principal": "林彦",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.550174,
      "longitude": 114.015671
  },
  {
      "number": 36,
      "name": "深圳市福田区教育传媒幼儿园",
      "created_time": "2021年08月",
      "address": "深圳市福田区莲花街道景田东路新媒体大厦西裙楼",
      "street": "莲花街道景华社区",
      "phone": 83148893,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "朱小曼",
      "principal": "朱小曼",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.551423,
      "longitude": 114.046344
  },
  {
      "number": 37,
      "name": "深圳市福田区金沙幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区沙头街道沙尾社区综合楼B栋2楼",
      "street": "沙头街道沙尾社区",
      "phone": 83550466,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "曹煜",
      "principal": "袁小红",
      "class": "规范园",
      "type": "区属公办园",
      "fee": 840,
      "latitude": 22.519655,
      "longitude": 114.041415
  },
  {
      "number": 38,
      "name": "深圳市福田区行学苑幼儿中心",
      "created_time": "2020年08月",
      "address": "深圳市福田区梅林街道深圳市建筑科学研究院股份有限公司建科大楼三楼",
      "street": "梅林街道孖岭社区",
      "phone": 23954706,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "赖方方",
      "principal": "赖方方",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.576125,
      "longitude": 114.058891
  },
  {
      "number": 39,
      "name": "中国人民解放军驻香港部队幼儿园",
      "created_time": "1997年07月",
      "address": "广东省深圳市福田区福保街道新港社区石厦四街1号",
      "street": "福保街道新港社区",
      "phone": 84481598,
      "organizer": "中国人民解放军75600部队",
      "legal_person": "部队",
      "principal": "高晶",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 2100,
      "latitude": 22.51832,
      "longitude": 114.054476
  },
  {
      "number": 40,
      "name": "深圳市福田区新城市春天幼儿园",
      "created_time": "2023年7月",
      "address": "深圳市福田区福华路南（福华路30号大院）荣超城市春天花园幼儿园整栋",
      "street": "福田街道圩镇社区",
      "phone": 83227732,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "吴海燕",
      "principal": "吴海燕",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.537053,
      "longitude": 114.081712
  },
  {
      "number": 41,
      "name": "深圳市福田区水榭花都幼儿园",
      "created_time": "2023年7月",
      "address": "福田区红荔路水榭花都",
      "street": "香蜜湖街道香蜜社区",
      "phone": 83052553,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "丁学丽",
      "principal": "丁学丽",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.545546,
      "longitude": 114.037607
  },
  {
      "number": 42,
      "name": "深圳市福田区天安实验幼儿园",
      "created_time": "2023年7月",
      "address": "福田区天安数码城泰然三路",
      "street": "沙头街道天安社区",
      "phone": 23966654,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "赖方方",
      "principal": "赖方方",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.531254,
      "longitude": 114.032901
  },
  {
      "number": 43,
      "name": "深圳市福田区香域中央幼儿园",
      "created_time": "2023年7月",
      "address": "深圳市福田区农园路68号",
      "street": "香蜜湖街道农园社区",
      "phone": 82708228,
      "organizer": "深圳市福田区第一幼儿园",
      "legal_person": "周道兰",
      "principal": "周道兰",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.549459,
      "longitude": 114.01696
  },
  {
      "number": 44,
      "name": "深圳市福田区第二实验学校附属幼儿园",
      "created_time": "2021年08月",
      "address": "深圳市福田区梅林街道梅坳四路6号",
      "street": "梅林街道孖岭社区",
      "phone": 83238326,
      "organizer": "深圳市福田区第二实验学校",
      "legal_person": "肖仕媚",
      "principal": "张宝玉",
      "class": "规范园",
      "type": "区属公办园",
      "fee": 840,
      "latitude": 22.574429,
      "longitude": 114.061254
  },
  {
      "number": 45,
      "name": "深圳市福田区东海实验小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区香轩路30号",
      "street": "香蜜湖街道东海社区",
      "phone": 23964784,
      "organizer": "深圳市福田区东海实验小学",
      "legal_person": "邓腊梅",
      "principal": "邓腊梅",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.539712,
      "longitude": 114.023463
  },
  {
      "number": 46,
      "name": "深圳市福田区福华小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区海田路4号港丽豪园西侧",
      "street": "福田街道福山社区",
      "phone": 83020261,
      "organizer": "深圳市福田区福华小学",
      "legal_person": "陈振朝",
      "principal": "马晓梅",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.530232,
      "longitude": 114.06602
  },
  {
      "number": 47,
      "name": "深圳市福田区福民小学附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区福强路福田街道1046号",
      "street": "福田街道海滨社区",
      "phone": 83832102,
      "organizer": "深圳市福田区福民小学",
      "legal_person": "王赟",
      "principal": "彭艳",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.524657,
      "longitude": 114.066372
  },
  {
      "number": 48,
      "name": "深圳市福田区福南小学附属幼儿园",
      "created_time": "2003年09月",
      "address": "深圳市福田区福田南路7号皇御苑小区内",
      "street": "福田街道口岸社区",
      "phone": 83859932,
      "organizer": "深圳市福田区福南小学",
      "legal_person": "耿媛",
      "principal": "李美红",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.527142,
      "longitude": 114.075219
  },
  {
      "number": 49,
      "name": "深圳市福田区福强小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区益田村71栋旁",
      "street": "福保街道益田社区",
      "phone": 83809912,
      "organizer": "深圳市福田区福强小学",
      "legal_person": "陈灵",
      "principal": "陈灵",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.515186,
      "longitude": 114.048824
  },
  {
      "number": 50,
      "name": "深圳市福田区福田小学附属幼儿园",
      "created_time": "2020年02月",
      "address": "广东省深圳市福田区福星路福祥街87号",
      "street": "福田街道福田社区",
      "phone": 83602826,
      "organizer": "深圳市福田区福田小学",
      "legal_person": "周静雯",
      "principal": "吴昊",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.534032,
      "longitude": 114.080363
  },
  {
      "number": 51,
      "name": "深圳市福田区福新小学第一附属幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区福田街道民田路2号",
      "street": "福田街道福安社区",
      "phone": 83221636,
      "organizer": "深圳市福田区福新小学",
      "legal_person": "吴颍丽",
      "principal": "吴颍丽",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.529328,
      "longitude": 114.05217
  },
  {
      "number": 52,
      "name": "深圳市福田区翰林实验学校附属幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区梅林路12号合正逸园小区内",
      "street": "梅林街道翰岭社区",
      "phone": 83248457,
      "organizer": "深圳市福田区翰林实验学校",
      "legal_person": "黄慧玲",
      "principal": "单丹",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.571172,
      "longitude": 114.070039
  },
  {
      "number": 53,
      "name": "深圳市福田区红岭中学（集团）石厦部附属幼",
      "created_time": "2020年08月",
      "address": "深圳市福田区沙头街道新洲南路金地海景花园",
      "street": "沙头街道翠湾社区",
      "phone": 23810600,
      "organizer": "深圳市福田区红岭中学（集团）",
      "legal_person": "蓝小昌",
      "principal": "梁玲",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.51522,
      "longitude": 114.041336
  },
  {
      "number": 54,
      "name": "深圳市福田区华强职业技术学校附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区红荔西路华新村31栋",
      "street": "华强北街道华红社区",
      "phone": 83255480,
      "organizer": "深圳市福田区华强职业技术学校",
      "legal_person": "郑莉娟",
      "principal": "郑莉娟",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 996,
      "latitude": 22.549944,
      "longitude": 114.083798
  },
  {
      "number": 55,
      "name": "深圳市福田区华新小学附属幼儿园",
      "created_time": "2022年01月",
      "address": "深圳市福田区滨河大道5006号",
      "street": "福田街道福山社区",
      "phone": 83268784,
      "organizer": "深圳市福田区华新小学",
      "legal_person": "冯运梅",
      "principal": "冯运梅",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.530952,
      "longitude": 114.0714
  },
  {
      "number": 56,
      "name": "深圳市福田区皇岗小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区福田街道皇岗村上围三村71号",
      "street": "福田街道皇岗社区",
      "phone": 83826111,
      "organizer": "深圳市福田区皇岗小学",
      "legal_person": "刘学金",
      "principal": "常艳",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.527095,
      "longitude": 114.061966
  },
  {
      "number": 57,
      "name": "深圳市福田区皇岗中学附属幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区皇岗公园街皇岗新村花园二期",
      "street": "福田街道皇岗社区",
      "phone": 83666926,
      "organizer": "深圳市福田区皇岗中学",
      "legal_person": "梁茜",
      "principal": "梁茜",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.521193,
      "longitude": 114.059681
  },
  {
      "number": 58,
      "name": "深圳市福田区黄埔学校附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区海田路1008号雅颂居内",
      "street": "莲花街道福中社区",
      "phone": 23485619,
      "organizer": "深圳市福田区黄埔学校",
      "legal_person": "夏若婷",
      "principal": "罗小兰",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.544355,
      "longitude": 114.067223
  },
  {
      "number": 59,
      "name": "深圳市福田区教育科学研究院附属幼儿园",
      "created_time": "2022年02月",
      "address": "深圳市福田区竹子林五路20号10栋",
      "street": "香蜜湖街道竹林社区",
      "phone": 83179333,
      "organizer": "深圳市福田区教育科学研究院附属小学",
      "legal_person": "邓柳娇",
      "principal": "邓柳娇",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.537637,
      "longitude": 114.009066
  },
  {
      "number": 60,
      "name": "深圳市福田区景莲小学附属幼儿园",
      "created_time": "2020年05月",
      "address": "景田北三街1号",
      "street": "莲花街道景田社区",
      "phone": 83911812,
      "organizer": "深圳市福田区景莲小学",
      "legal_person": "马波",
      "principal": "张宏东",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.558175,
      "longitude": 114.043597
  },
  {
      "number": 61,
      "name": "深圳市福田区景龙小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区红荔西路香蜜三村",
      "street": "莲花街道紫荆社区",
      "phone": 82550492,
      "organizer": "深圳市福田区景龙小学",
      "legal_person": "黄慧君",
      "principal": "刘梅玫",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.545197,
      "longitude": 114.046967
  },
  {
      "number": 62,
      "name": "深圳市福田区景鹏小学附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区莲花街道福中三路3018号",
      "street": "莲花街道福新社区",
      "phone": 82987399,
      "organizer": "深圳市福田区景鹏小学",
      "legal_person": "梁丽芳",
      "principal": "梁丽芳",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.542807,
      "longitude": 114.050161
  },
  {
      "number": 63,
      "name": "深圳市福田区景田小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区莲花街道景田北路景田西住宅区内",
      "street": "莲花街道景田社区",
      "phone": 83900620,
      "organizer": "深圳市福田区景田小学",
      "legal_person": "李林英",
      "principal": "罗雪",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.557194,
      "longitude": 114.041115
  },
  {
      "number": 64,
      "name": "深圳市福田区科技中学附属幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区福中一路3011号",
      "street": "莲花街道福新社区",
      "phone": 82794035,
      "organizer": "深圳市福田区科技中学",
      "legal_person": "张丽琴",
      "principal": "张丽琴",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.546176,
      "longitude": 114.050185
  },
  {
      "number": 65,
      "name": "深圳市福田区荔园教育集团百花校区附属幼儿",
      "created_time": "2020年02月",
      "address": "福田区百花二路南天大厦5-6栋之间",
      "street": "园岭街道南天社区",
      "phone": 83201078,
      "organizer": "深圳市福田区荔园教育集团",
      "legal_person": "周静雯",
      "principal": "周静雯",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.550476,
      "longitude": 114.094028
  },
  {
      "number": 66,
      "name": "深圳市福田区荔园教育集团附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区新洲二街19号",
      "street": "沙头街道新洲社区",
      "phone": 23913396,
      "organizer": "深圳市福田区荔园教育集团",
      "legal_person": "向兵",
      "principal": "朱湘辽",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.520486,
      "longitude": 114.045842
  },
  {
      "number": 67,
      "name": "深圳市福田区荔园外国语小学东校区附属幼儿",
      "created_time": "2020年05月",
      "address": "深圳市福田区香梅路香蜜湖一号",
      "street": "香蜜湖街道香蜜社区",
      "phone": 83207345,
      "organizer": "深圳市福田区荔园外国语小学",
      "legal_person": "陈亚男",
      "principal": "陈亚男",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.55129,
      "longitude": 114.036418
  },
  {
      "number": 68,
      "name": "深圳市福田区荔园外国语小学狮岭校区附属幼",
      "created_time": "2020年01月",
      "address": "福田区景田东路2号",
      "street": "莲花街道紫荆社区",
      "phone": 83902758,
      "organizer": "深圳市福田区荔园外国语小学",
      "legal_person": "卢亮辉",
      "principal": "杜心意",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.542031,
      "longitude": 114.047492
  },
  {
      "number": 69,
      "name": "深圳市福田区荔园外国语小学西校区附属幼儿",
      "created_time": "2020年05月",
      "address": "深圳市福田区香蜜湖街道香蜜社区香庭二街3012号熙园",
      "street": "香蜜湖街道香蜜社区",
      "phone": 82890649,
      "organizer": "深圳市福田区荔园外国语小学",
      "legal_person": "张建军",
      "principal": "张建军",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.549044,
      "longitude": 114.026152
  },
  {
      "number": 70,
      "name": "深圳市福田区绿洲小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区沙嘴村3坊35号",
      "street": "沙头街道沙嘴社区",
      "phone": 83408060,
      "organizer": "深圳市福田区绿洲小学",
      "legal_person": "黄科",
      "principal": "黄科",
      "class": "规范园",
      "type": "区属公办园",
      "fee": 840,
      "latitude": 22.516415,
      "longitude": 114.037572
  },
  {
      "number": 71,
      "name": "深圳市福田区梅丽小学附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区彩田路1号",
      "street": "梅林街道翰岭社区",
      "phone": 23993029,
      "organizer": "深圳市福田区梅丽小学",
      "legal_person": "王勇",
      "principal": "杨璠",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 960,
      "latitude": 22.572325,
      "longitude": 114.067033
  },
  {
      "number": 72,
      "name": "深圳市福田区梅林小学附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区梅林街道梅林二村梅育路68号",
      "street": "梅林街道梅河社区",
      "phone": 83110314,
      "organizer": "深圳市福田区梅林小学",
      "legal_person": "郄超",
      "principal": "袁美英",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.564987,
      "longitude": 114.042852
  },
  {
      "number": 73,
      "name": "深圳市福田区梅园小学附属幼儿园",
      "created_time": "2011年07月",
      "address": "福田区梅林街道梅北路40号",
      "street": "梅林街道梅都社区",
      "phone": 28997522,
      "organizer": "深圳市福田区梅园小学",
      "legal_person": "肖仕媚",
      "principal": "肖仕媚",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.571163,
      "longitude": 114.046992
  },
  {
      "number": 74,
      "name": "深圳市福田区美莲小学附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区笋岗西路4003号莲花一村内",
      "street": "华富街道莲花一村社区",
      "phone": 83253374,
      "organizer": "深圳市福田区美莲小学",
      "legal_person": "常河",
      "principal": "常河",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.553413,
      "longitude": 114.071027
  },
  {
      "number": 75,
      "name": "深圳市福田区全海小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "福田区益田村48栋旁",
      "street": "福保街道益田社区",
      "phone": 88602212,
      "organizer": "深圳市福田区全海小学",
      "legal_person": "朱珊",
      "principal": "朱珊",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.513112,
      "longitude": 114.048405
  },
  {
      "number": 76,
      "name": "深圳市福田区上沙小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区上沙龙秋村四巷1号",
      "street": "沙头街道上沙社区",
      "phone": 83308717,
      "organizer": "深圳市福田区上沙小学",
      "legal_person": "刘青",
      "principal": "刘志清",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.523929,
      "longitude": 114.032761
  },
  {
      "number": 77,
      "name": "深圳市福田区石厦学校附属幼儿园",
      "created_time": "2020年02月",
      "address": "石厦东村247号",
      "street": "福保街道石厦社区",
      "phone": 83830161,
      "organizer": "深圳市福田区石厦学校",
      "legal_person": "刘院英",
      "principal": "刘院英",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.520504,
      "longitude": 114.051646
  },
  {
      "number": 78,
      "name": "深圳市福田区实验教育集团附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区侨香路枫丹雅苑小区内",
      "street": "香蜜湖街道香梅社区",
      "phone": 83158264,
      "organizer": "深圳市福田区实验教育集团",
      "legal_person": "李陈陈",
      "principal": "钟金兰",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.553185,
      "longitude": 114.023115
  },
  {
      "number": 79,
      "name": "深圳市福田区水围小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区益田路2004号共和世家小区内水围小学附属幼儿园",
      "street": "福田街道皇岗社区",
      "phone": 23984427,
      "organizer": "深圳市福田区水围小学",
      "legal_person": "李捷夏",
      "principal": "李捷夏",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.521506,
      "longitude": 114.057813
  },
  {
      "number": 80,
      "name": "深圳市福田区天健小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区福中一路深业花园内",
      "street": "莲花街道福中社区",
      "phone": 83796180,
      "organizer": "深圳市福田区天健小学",
      "legal_person": "仇亚萍",
      "principal": "仇亚萍",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.546439,
      "longitude": 114.067413
  },
  {
      "number": 81,
      "name": "深圳市福田区外国语高级中学附属幼儿园",
      "created_time": "2020年05月",
      "address": "福田区外国语高级中学附属幼儿园",
      "street": "福保街道益田社区",
      "phone": 88602920,
      "organizer": "深圳市福田区外国语高级中学",
      "legal_person": "吴雪燕",
      "principal": "方艳平",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.51495,
      "longitude": 114.047523
  },
  {
      "number": 82,
      "name": "深圳市福田区外国语学校北校区附属幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区莲花街道景田六片区",
      "street": "莲花街道康欣社区",
      "phone": 83933812,
      "organizer": "深圳市福田区外国语学校",
      "legal_person": "凌玉珊",
      "principal": "丘鸿燕",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.554883,
      "longitude": 114.039638
  },
  {
      "number": 83,
      "name": "深圳市福田区外国语学校附属幼儿园",
      "created_time": "2003年09月",
      "address": "深圳市福田区益田豪园居小区内",
      "street": "福保街道福保街道",
      "phone": 22664905,
      "organizer": "深圳市福田区外国语学校",
      "legal_person": "王东晓",
      "principal": "黄慧",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.554883,
      "longitude": 114.039638
  },
  {
      "number": 84,
      "name": "深圳市福田区下沙小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区沙头街道下沙社区一坊108号",
      "street": "沙头街道下沙社区",
      "phone": 83405705,
      "organizer": "深圳市福田区下沙小学",
      "legal_person": "姚莉",
      "principal": "陈菲菲",
      "class": "区一级",
      "type": "区属公办园",
      "fee": 924,
      "latitude": 22.526828,
      "longitude": 114.025464
  },
  {
      "number": 85,
      "name": "深圳市福田区新沙小学第二附属幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区新洲九街绿景新苑",
      "street": "沙头街道新洲社区",
      "phone": 88300323,
      "organizer": "深圳市福田区新沙小学",
      "legal_person": "吴辉斌",
      "principal": "吴辉斌",
      "class": "规范园",
      "type": "区属公办园",
      "fee": 840,
      "latitude": 22.524156,
      "longitude": 114.045648
  },
  {
      "number": 86,
      "name": "深圳市福田区新沙小学附属幼儿园",
      "created_time": "2020年05月",
      "address": "福田区新洲七街124号",
      "street": "沙头街道新华社区",
      "phone": 83417747,
      "organizer": "深圳市福田区新沙小学",
      "legal_person": "王赟",
      "principal": "王赟",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.523539,
      "longitude": 114.041337
  },
  {
      "number": 87,
      "name": "深圳市福田区新洲小学附属幼儿园",
      "created_time": "2003年08月",
      "address": "深圳市福田区沙头街道都市花园御庭轩",
      "street": "沙头街道新沙社区",
      "phone": 83552075,
      "organizer": "深圳市福田区新洲小学",
      "legal_person": "文佳",
      "principal": "文佳",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.516415,
      "longitude": 114.037572
  },
  {
      "number": 88,
      "name": "深圳市福田区新洲中学附属幼儿园",
      "created_time": "2020年08月",
      "address": "深圳市福田区新洲四街125号",
      "street": "沙头街道新华社区",
      "phone": 83413147,
      "organizer": "深圳市福田区新洲中学",
      "legal_person": "曹煜",
      "principal": "吕媛",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.525881,
      "longitude": 114.042042
  },
  {
      "number": 89,
      "name": "深圳市福田区益强小学附属幼儿园",
      "created_time": "2020年02月",
      "address": "深圳市福田区福荣路62号",
      "street": "沙头街道金碧社区",
      "phone": 88302611,
      "organizer": "深圳市福田区益强小学",
      "legal_person": "胡慧",
      "principal": "舒丽萍",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.522497,
      "longitude": 114.026616
  },
  {
      "number": 90,
      "name": "深圳市福田区益田小学附属幼儿园",
      "created_time": "2020年01月",
      "address": "深圳市福田区益田村24栋对面",
      "street": "福保街道益田社区",
      "phone": 82870296,
      "organizer": "深圳市福田区益田小学",
      "legal_person": "朱珊",
      "principal": "朱珊",
      "class": "市一级",
      "type": "区属公办园",
      "fee": 966,
      "latitude": 22.513655,
      "longitude": 114.052987
  },
  {
      "number": 91,
      "name": "深圳市福田区园岭实验小学附属幼儿园",
      "created_time": "2020年05月",
      "address": "深圳市福田区园岭东路园岭七街4号",
      "street": "园岭街道园东社区",
      "phone": 82349039,
      "organizer": "深圳市福田区园岭实验小学",
      "legal_person": "李嘉",
      "principal": "邵晓如",
      "class": "省一级",
      "type": "区属公办园",
      "fee": 1008,
      "latitude": 22.554143,
      "longitude": 114.102995
  },
  {
      "number": 92,
      "name": "深圳市福田区金盾第一幼儿园",
      "created_time": "2023年5月",
      "address": "深圳市福田区华富街道新田社区深南大道1018号",
      "street": "华富街道新田社区",
      "phone": 83998951,
      "organizer": "深圳市福田区学前教育发展中心",
      "legal_person": "卢亮辉",
      "principal": "卢亮辉",
      "class": "未评级",
      "type": "区属公办园",
      "fee": 840,
      "latitude": 22.541888,
      "longitude": 114.068388
  },
  {
      "number": 93,
      "name": "深圳市福田区福堤幼儿园",
      "created_time": "在建",
      "type": "区属公办园",
      "fee": "/",
      "latitude": 22.516425,
      "longitude": 114.065692
  },
  {
      "number": 94,
      "name": "深圳市福田区九曜幼儿园",
      "created_time": "在建",
      "type": "区属公办园",
      "fee": "/"
  },
  {
      "number": 95,
      "name": "深圳市福田区水围幼儿园",
      "created_time": "在建",
      "type": "区属公办园",
      "fee": "/"
  },
  {
      "number": 96,
      "name": "深圳市景山幼儿园",
      "created_time": "2002年09月",
      "address": "深圳市福田区深南大道田面村绿洲花园旁",
      "street": "华富街道田面社区",
      "phone": 83245644,
      "organizer": "深圳市富德森金融服务有限公司",
      "legal_person": "陈晓思",
      "principal": "聂玉兰",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1700,
      "latitude": 22.542668,
      "longitude": 114.076444
  },
  {
      "number": 97,
      "name": "深圳市福田区博雅名津幼儿园",
      "created_time": "2012年03月",
      "address": "深圳市福田区渔农村名津广场内",
      "street": "福田街道渔农社区",
      "phone": 82564756,
      "organizer": "深圳市福田区博雅教育机构",
      "legal_person": "姚建造",
      "principal": "黄小丹",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.516933,
      "longitude": 114.073259
  },
  {
      "number": 98,
      "name": "深圳市福田区天健香蜜幼儿园",
      "created_time": "1999年09月",
      "address": "福田区红荔西路香蜜新村内",
      "street": "莲花街道狮岭社区",
      "phone": 83913558,
      "organizer": "深圳市天健（集团）股份有限公司",
      "legal_person": "张卫国",
      "principal": "张艳丽",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.547225,
      "longitude": 114.040645
  },
  {
      "number": 99,
      "name": "深圳市福田区慧文幼儿园",
      "created_time": "2008年07月",
      "address": "深圳市福田区农林路57号佳泰兴苑小区旁",
      "street": "香蜜湖街道竹园社区",
      "phone": 83707797,
      "organizer": "深圳市海德堡投资发展有限公司",
      "legal_person": "张绮婵",
      "principal": "张绮婵",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.541648,
      "longitude": 114.012921
  },
  {
      "number": 100,
      "name": "深圳市福田区盛世鹏程幼儿园",
      "created_time": "2007年06月",
      "address": "深圳市福田区八卦一路盛世鹏程花园东区盛世鹏程幼儿园",
      "street": "园岭街道鹏盛社区",
      "phone": 22303844,
      "organizer": "深圳市赛兔数码科技有限公司",
      "legal_person": "张仁仪",
      "principal": "钟丽优",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1500,
      "latitude": 22.556472,
      "longitude": 114.098784
  },
  {
      "number": 101,
      "name": "深圳市福田区华庭思博幼儿园",
      "created_time": "2012年12月",
      "address": "福田区民田路10号中海华庭小区",
      "street": "福田街道福安社区",
      "phone": 82490457,
      "organizer": "张彦婷",
      "legal_person": "张彦婷",
      "principal": "毛宁娟",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1500,
      "latitude": 22.532868,
      "longitude": 114.05134
  },
  {
      "number": 102,
      "name": "深圳市福田区丽辉幼儿园",
      "created_time": "2007年01月",
      "address": "深圳市福田区海滨广场皇岗花园首层",
      "street": "福田街道海滨社区",
      "phone": 88306216,
      "organizer": "朱良开",
      "legal_person": "朱良开",
      "principal": "林莉莉",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1000,
      "latitude": 22.527794,
      "longitude": 114.064834
  },
  {
      "number": 103,
      "name": "深圳市福田区佳音香榭里幼儿园",
      "created_time": "2010年09月",
      "address": "深圳市福田区丰田路2号",
      "street": "香蜜湖街道农园社区",
      "phone": 82733286,
      "organizer": "深圳市豆豆村学期教育研究开发有限公司",
      "legal_person": "张湘红",
      "principal": "张湘红",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1600,
      "latitude": 22.543641,
      "longitude": 114.020355
  },
  {
      "number": 104,
      "name": "深圳市福田区美加碧华儿童中心幼儿园",
      "created_time": "2001年08月",
      "address": "深圳市福田区上梅林梅秀路碧华庭居小区",
      "street": "梅林街道梅丰社区",
      "phone": 83164417,
      "organizer": "美加儿童俱乐部（深圳）有限公司",
      "legal_person": "张玮",
      "principal": "刘春红",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.564061,
      "longitude": 114.049198
  },
  {
      "number": 105,
      "name": "深圳市福田区天御香山幼儿园",
      "created_time": "2016年08月",
      "address": "深圳市福田区香蜜湖街道农轩路31号",
      "street": "香蜜湖街道东海社区",
      "phone": 23999121,
      "organizer": "深圳市马荣教育机构实业发展有限公司",
      "legal_person": "吴义生",
      "principal": "卢峻",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.538268,
      "longitude": 114.020307
  },
  {
      "number": 106,
      "name": "深圳市振业梅苑幼儿园",
      "created_time": "1999年05月",
      "address": "福田区上梅林广厦路十号",
      "street": "梅林街道梅亭社区",
      "phone": 83109727,
      "organizer": "杜先芬",
      "legal_person": "杜先芬",
      "principal": "曲秀敏",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1500,
      "latitude": 22.566288,
      "longitude": 114.060229
  },
  {
      "number": 107,
      "name": "深圳市福田区新天力园中幼儿园",
      "created_time": "1997年09月",
      "address": "深圳市福田区园岭街道园中花园A栋三楼",
      "street": "园岭街道红荔社区",
      "phone": 25881650,
      "organizer": "刘荔",
      "legal_person": "刘荔",
      "principal": "吴颖佳",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1267,
      "latitude": 22.552156,
      "longitude": 114.098336
  },
  {
      "number": 108,
      "name": "深圳市福田区菁菁托儿所",
      "created_time": "2001年08月",
      "address": "深圳市福田区沙头街道金地一路18-1号",
      "street": "沙头街道翠湾社区",
      "phone": 83857187,
      "organizer": "冯素文",
      "legal_person": "冯素文",
      "principal": "戴芬芬",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 750,
      "latitude": 22.516806,
      "longitude": 114.041773
  },
  {
      "number": 109,
      "name": "深圳市福田区根深叶茂幼儿园",
      "created_time": "2002年02月",
      "address": "深圳市福田区下梅林龙尾路福兴花园小区",
      "street": "梅林街道龙尾社区",
      "phone": 83186968,
      "organizer": "何爱兵",
      "legal_person": "何爱兵",
      "principal": "袁燕",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1600,
      "latitude": 22.569647,
      "longitude": 114.044609
  },
  {
      "number": 110,
      "name": "深圳市福田区温新幼儿园",
      "created_time": "2002年06月",
      "address": "深圳市福田区沙尾西村399号",
      "street": "沙头街道沙尾社区",
      "phone": 82777620,
      "organizer": "易凌",
      "legal_person": "易凌",
      "principal": "吴春红",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 750,
      "latitude": 22.517476,
      "longitude": 114.042416
  },
  {
      "number": 111,
      "name": "深圳市福田区金色童年金众幼儿园",
      "created_time": "2010年07月",
      "address": "福田区竹子林金众小区48栋",
      "street": "香蜜湖街道竹林社区",
      "phone": 83500055,
      "organizer": "黄志莲",
      "legal_person": "黄志莲",
      "principal": "洪巧敏",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1000,
      "latitude": 22.53782,
      "longitude": 114.011461
  },
  {
      "number": 112,
      "name": "深圳市福田区碧海云天幼儿园",
      "created_time": "2003年09月",
      "address": "深圳市侨城东路碧海云天小区",
      "street": "沙头街道金城社区",
      "phone": 22677987,
      "organizer": "深圳市冠萃教育发展有限公司",
      "legal_person": "吴妍燊",
      "principal": "吴妍燊",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.529509,
      "longitude": 113.997098
  },
  {
      "number": 113,
      "name": "深圳市福田区福祥幼儿园",
      "created_time": "1995年09月",
      "address": "深圳市福田区福星路福祥街5号3楼",
      "street": "福田街道福田社区",
      "phone": 88290996,
      "organizer": "福田房地产有限公司",
      "legal_person": "王延亭",
      "principal": "侯淑琼",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1200,
      "latitude": 22.531786,
      "longitude": 114.082414
  },
  {
      "number": 114,
      "name": "深圳市福田区丽阳幼儿园",
      "created_time": "2008年03月",
      "address": "深圳市福田区石厦北四街六号丽阳天下名苑裙楼二层",
      "street": "福保街道明月社区",
      "phone": 83482152,
      "organizer": "郑亮",
      "legal_person": "郑亮",
      "principal": "黄彩云",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1300,
      "latitude": 22.525129,
      "longitude": 114.051264
  },
  {
      "number": 115,
      "name": "深圳市福田区天爱幼儿园",
      "created_time": "2014年12月",
      "address": "福田区皇岗路岗厦高科利花园大厦裙楼",
      "street": "福田街道文山社区",
      "phone": 88360398,
      "organizer": "李剑英、谭文雄",
      "legal_person": "李剑英",
      "principal": "黄柳",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1700,
      "latitude": 22.536186,
      "longitude": 114.072257
  },
  {
      "number": 116,
      "name": "深圳市福田区贝贝龙幼儿园",
      "created_time": "2000年11月",
      "address": "深圳市福田区香蜜湖西侧农科中心内",
      "street": "香蜜湖街道农园社区",
      "phone": 83701977,
      "organizer": "范淑丽",
      "legal_person": "范淑丽",
      "principal": "何丽韦",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1200,
      "latitude": 22.544394,
      "longitude": 114.01634
  },
  {
      "number": 117,
      "name": "深圳市福田区梅山苑幼儿园",
      "created_time": "2014年12月",
      "address": "深圳市福田区下梅林梅山苑二期小区内",
      "street": "梅林街道梅京社区",
      "phone": 23996678,
      "organizer": "蔡水冰",
      "legal_person": "李映格",
      "principal": "陈利",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1440,
      "latitude": 22.564738,
      "longitude": 114.030245
  },
  {
      "number": 118,
      "name": "深圳市基建幼儿园",
      "created_time": "1985年11月",
      "address": "深圳市福田区园岭五街六号",
      "street": "园岭街道红荔社区",
      "phone": 22204209,
      "organizer": "深圳市长虹投资有限公司",
      "legal_person": "郑碧琴",
      "principal": "郑碧琴",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.553436,
      "longitude": 114.098159
  },
  {
      "number": 119,
      "name": "深圳市福田区乐贝尔幼儿园",
      "created_time": "2018年06月",
      "address": "深圳市福田区福田街道福田社区大门坊72号福兴楼",
      "street": "福田街道福田社区",
      "phone": 83254981,
      "organizer": "深圳市乐贝尔教育实业有限公司",
      "legal_person": "崔海杰",
      "principal": "杨鸿霞",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.529856,
      "longitude": 114.081472
  },
  {
      "number": 120,
      "name": "深圳市福田区铭阳盛世幼儿园",
      "created_time": "2004年09月",
      "address": "深圳市福田区长城盛世家园二期",
      "street": "莲花街道彩虹社区",
      "phone": 82894889,
      "organizer": "深圳前海铭阳国际教育投资有限公司",
      "legal_person": "邬莉娜",
      "principal": "邬莉娜",
      "class": "省一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.561547,
      "longitude": 114.065062
  },
  {
      "number": 121,
      "name": "深圳市福田区佳茗幼儿园",
      "created_time": "2007年04月",
      "address": "深圳市福田区梅华路235号",
      "street": "梅林街道下梅社区",
      "phone": 83100229,
      "organizer": "张向铭",
      "legal_person": "张向铭",
      "principal": "傅志娇",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 800,
      "latitude": 22.561978,
      "longitude": 114.043959
  },
  {
      "number": 122,
      "name": "深圳市福田区博蕾福星幼儿园",
      "created_time": "2010年09月",
      "address": "深圳市福田区福星花园大厦裙楼301、302",
      "street": "福田街道福华社区",
      "phone": 88297329,
      "organizer": "张彬",
      "legal_person": "张彬",
      "principal": "朱艳",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1200,
      "latitude": 22.535171,
      "longitude": 114.082823
  },
  {
      "number": 123,
      "name": "深圳市福田区歌丽幼儿园",
      "created_time": "2005年10月",
      "address": "深圳市福田区景田西路赛格景苑",
      "street": "莲花街道康欣社区",
      "phone": 83933090,
      "organizer": "格林绿岛教育发展（深圳）有限公司",
      "legal_person": "邓玉红",
      "principal": "邓鑫",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1500,
      "latitude": 22.554385,
      "longitude": 114.037373
  },
  {
      "number": 124,
      "name": "深圳市曼京幼儿园",
      "created_time": "1998年08月",
      "address": "广东省深圳市福田区上梅林梅华路梅兴苑",
      "street": "梅林街道新兴社区",
      "phone": 83313247,
      "organizer": "黄永玉",
      "legal_person": "黄永玉",
      "principal": "夏凡",
      "class": "省一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.565981,
      "longitude": 114.051063
  },
  {
      "number": 125,
      "name": "深圳市福田区金安幼儿园",
      "created_time": "1999年07月",
      "address": "深圳市福田区福景路金安花园Ｂ栋一楼金安幼儿园",
      "street": "福田街道福华社区",
      "phone": 88296599,
      "organizer": "陈胜坚",
      "legal_person": "陈胜坚",
      "principal": "李胜云",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1500,
      "latitude": 22.535665,
      "longitude": 114.083801
  },
  {
      "number": 126,
      "name": "深圳市福田区小太阳幼儿园",
      "created_time": "2007年07月",
      "address": "深圳市福田区梅林二村16栋2楼",
      "street": "梅林街道梅河社区",
      "phone": 83117261,
      "organizer": "鲁成安",
      "legal_person": "鲁成安",
      "principal": "梁静",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1000,
      "latitude": 22.56453,
      "longitude": 114.043905
  },
  {
      "number": 127,
      "name": "深圳市福田区侨香一冶广场幼儿园",
      "created_time": "2016年03月",
      "address": "深圳市福田区侨香路与广深高速公路交汇处",
      "street": "香蜜湖街道香安社区",
      "phone": 83255576,
      "organizer": "深圳市马荣教育发展有限公司",
      "legal_person": "张莹莹",
      "principal": "旃娟",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.542574,
      "longitude": 113.999012
  },
  {
      "number": 128,
      "name": "深圳长城幼儿园",
      "created_time": "1995年07月",
      "address": "深圳市福田区百花四路10号",
      "street": "园岭街道长城社区",
      "phone": 83210051,
      "organizer": "深圳市佳金旺投资发展有限公司",
      "legal_person": "方锦奎",
      "principal": "宁晓微",
      "class": "省一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.551851,
      "longitude": 114.088358
  },
  {
      "number": 129,
      "name": "深圳市福田区光彩幼儿园",
      "created_time": "1998年09月",
      "address": "深圳市福田区南园街道滨河新村光彩幼儿园",
      "street": "南园街道滨江社区",
      "phone": 82276067,
      "organizer": "陈丽珊",
      "legal_person": "陈丽珊",
      "principal": "周瑰",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1500,
      "latitude": 22.536519,
      "longitude": 114.103239
  },
  {
      "number": 130,
      "name": "深圳市福田区辅英龙幼儿园",
      "created_time": "2014年09月",
      "address": "福田区彩福大厦一楼",
      "street": "福田街道岗厦社区",
      "phone": 83174119,
      "organizer": "刘冠城",
      "legal_person": "刘冠城",
      "principal": "李慧连",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1480,
      "latitude": 22.536302,
      "longitude": 114.067374
  },
  {
      "number": 131,
      "name": "深圳市福田区新趋势鹏盛年华幼儿园",
      "created_time": "2007年06月",
      "address": "深圳市福田区八卦路2号",
      "street": "园岭街道鹏盛社区",
      "phone": 82298670,
      "organizer": "深圳丽晶投资有限公司",
      "legal_person": "张彦婷",
      "principal": "蒋金花",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1780,
      "latitude": 22.556449,
      "longitude": 114.100123
  },
  {
      "number": 132,
      "name": "深圳市福田区福莲幼儿园",
      "created_time": "2003年07月",
      "address": "深圳市福田区红荔西路福莲花园",
      "street": "华富街道莲花三村社区",
      "phone": 83257680,
      "organizer": "陈舜琦",
      "legal_person": "陈舜琦",
      "principal": "丘素琼",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1650,
      "latitude": 22.547602,
      "longitude": 114.0695
  },
  {
      "number": 133,
      "name": "深圳市福田区华茂苑茗苑幼儿园",
      "created_time": "2001年02月",
      "address": "深圳市福田区中康路1号华茂苑8栋一楼西侧",
      "street": "梅林街道梅丰社区",
      "phone": 83313980,
      "organizer": "李燕华",
      "legal_person": "李燕华",
      "principal": "吴小琴",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1100,
      "latitude": 22.563324,
      "longitude": 114.056763
  },
  {
      "number": 134,
      "name": "深圳市福田区汇龙幼儿园",
      "created_time": "1999年09月",
      "address": "深圳市福田区上梅林凯丰路北30号汇龙花内",
      "street": "梅林街道孖岭社区",
      "phone": 83528782,
      "organizer": "刘宁",
      "legal_person": "刘宁",
      "principal": "辜凤梅",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1600,
      "latitude": 22.574046,
      "longitude": 114.063975
  },
  {
      "number": 135,
      "name": "深圳市福田区大风车幼儿园",
      "created_time": "2008年12月",
      "address": "深圳市福田区景田南综合楼二楼201号",
      "street": "莲花街道景田社区",
      "phone": 83903456,
      "organizer": "张清华",
      "legal_person": "张清华",
      "principal": "朱小文",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1400,
      "latitude": 22.556873,
      "longitude": 114.044685
  },
  {
      "number": 136,
      "name": "深圳市福田区锦林幼儿园",
      "created_time": "1999年09月",
      "address": "福田区梅林街道下梅林锦林新居内",
      "street": "梅林街道下梅社区",
      "phone": 83108976,
      "organizer": "马克荣",
      "legal_person": "马克荣",
      "principal": "仲晓",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.562348,
      "longitude": 114.040252
  },
  {
      "number": 137,
      "name": "深圳市福田区东方幼儿园",
      "created_time": "1993年07月",
      "address": "深圳市福田区八卦中路四栋西侧一楼",
      "street": "园岭街道上林社区",
      "phone": 82423273,
      "organizer": "蒋英秀",
      "legal_person": "杨凯鸥",
      "principal": "沈红",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 950,
      "latitude": 22.560829,
      "longitude": 114.099808
  },
  {
      "number": 138,
      "name": "深圳市福田区竟智幼儿园",
      "created_time": "2008年04月",
      "address": "深圳市福田区福强路福民新村福昌大厦二楼竟智幼儿园",
      "street": "福田街道福民社区",
      "phone": 83558192,
      "organizer": "王耀波",
      "legal_person": "王耀波",
      "principal": "吴月华",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1200,
      "latitude": 22.525106,
      "longitude": 114.070063
  },
  {
      "number": 139,
      "name": "深圳市福田区华原幼儿园",
      "created_time": "2002年09月",
      "address": "梅林四村小区内",
      "street": "梅林街道上梅社区",
      "phone": 83312411,
      "organizer": "余姣英",
      "legal_person": "余姣英",
      "principal": "余姣英",
      "class": "规范园",
      "type": "民办普惠园",
      "fee": 1300,
      "latitude": 22.567847,
      "longitude": 114.054879
  },
  {
      "number": 140,
      "name": "深圳市福田区岗厦幼儿园",
      "created_time": "2002年09月",
      "address": "深圳市福田区福田街道岗厦社区岗厦村东四坊21号",
      "street": "福田街道岗厦社区",
      "phone": 88362398,
      "organizer": "陈胜坚",
      "legal_person": "陈胜坚",
      "principal": "王成林",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1260,
      "latitude": 22.536851,
      "longitude": 114.068942
  },
  {
      "number": 141,
      "name": "深圳市福田区云顶翠峰幼儿园",
      "created_time": "2005年12月",
      "address": "深圳市福田区皇岗公园一街云顶翠峰二期小区内",
      "street": "福田街道皇岗社区",
      "phone": 83846379,
      "organizer": "王国英",
      "legal_person": "王国英",
      "principal": "常笑岩",
      "class": "区一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.518382,
      "longitude": 114.061431
  },
  {
      "number": 142,
      "name": "深圳市福田区御景华城幼儿园",
      "created_time": "2008年09月",
      "address": "深圳市福田区华强南路御景华城小区",
      "street": "南园街道赤尾社区",
      "phone": 82515173,
      "organizer": "深圳市英贝教育发展有限公司",
      "legal_person": "王斌",
      "principal": "刘全珍",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1800,
      "latitude": 22.53244,
      "longitude": 114.086531
  },
  {
      "number": 143,
      "name": "深圳市福田区华茂苑幼儿园",
      "created_time": "2021年02月",
      "address": "深圳市福田区梅林三村4栋",
      "street": "梅林街道新兴社区",
      "phone": 83142436,
      "organizer": "李泗芳",
      "legal_person": "李泗芳",
      "principal": "李燕华",
      "class": "市一级",
      "type": "民办普惠园",
      "fee": 1400,
      "latitude": 22.568397,
      "longitude": 114.052103
  },
  {
      "number": 144,
      "name": "深圳市福田区杰莘幼儿园",
      "created_time": "2021年08月",
      "address": "深圳市福田区东园路台湾花园裙楼三层11号、12号、13号、14号",
      "street": "南园街道巴登社区",
      "phone": 22271078,
      "organizer": "陈汉坤",
      "legal_person": "陈汉坤",
      "principal": "刘淑华",
      "class": "未评级",
      "type": "民办普惠园",
      "fee": 1500,
      "latitude": 22.537167,
      "longitude": 114.102017
  },
  {
      "number": 145,
      "name": "深圳市福田区曙光私立幼儿园",
      "created_time": "1991年12月",
      "address": "深圳市福田区松岭路56-1号南园大楼1-4楼",
      "street": "南园街道滨江社区",
      "phone": 83625378,
      "organizer": "关晓红",
      "legal_person": "关晓红",
      "principal": "伍小羽",
      "class": "未评级",
      "type": "民办非普惠园",
      "fee": 1050,
      "latitude": 22.538197,
      "longitude": 114.095073
  },
  {
      "number": 146,
      "name": "深圳市特发幼儿园",
      "created_time": "1998年08月",
      "address": "深圳市福田区香梅北路特发小区香蜜湖街道香梅社区",
      "street": "香蜜湖街道香蜜社区",
      "phone": 83180098,
      "organizer": "深圳市物业管理有限公司",
      "legal_person": "杨晓玲",
      "principal": "杨晓玲",
      "class": "省一级",
      "type": "民办非普惠园",
      "fee": 2300,
      "latitude": 22.554619,
      "longitude": 114.030038
  },
  {
      "number": 147,
      "name": "深圳市金海湾幼儿园",
      "created_time": "2002年04月",
      "address": "深圳市福田区海滨沙嘴金海湾花园内",
      "street": "沙头街道金地社区",
      "phone": 83842820,
      "organizer": "深圳市马荣天使投资有限公司",
      "legal_person": "吴义生",
      "principal": "惠江红",
      "class": "省一级",
      "type": "民办非普惠园",
      "fee": 4000,
      "latitude": 22.519274,
      "longitude": 114.034075
  },
  {
      "number": 148,
      "name": "深圳市福田区瀚盛吉纽思幼儿园",
      "created_time": "2010年06月",
      "address": "深圳市福田区香水三街2号瀚盛吉纽思幼儿园",
      "street": "香蜜湖街道香梅社区",
      "phone": 82562631,
      "organizer": "叶晓菊",
      "legal_person": "叶晓菊",
      "principal": "肖晓群",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 4140,
      "latitude": 22.556616,
      "longitude": 114.021876
  },
  {
      "number": 149,
      "name": "深圳市福田区铭爵幼儿园有限公司",
      "created_time": "2021年09月",
      "address": "深圳市福田区百花四路4号",
      "street": "园岭街道长城社区",
      "phone": 83363870,
      "organizer": "穆佳怡",
      "legal_person": "张保庆",
      "principal": "王艳霞",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 2500,
      "latitude": 22.553509,
      "longitude": 114.090012
  },
  {
      "number": 150,
      "name": "深圳市福田区鹏城幼儿园有限公司",
      "created_time": "2019年04月",
      "address": "深圳市福田区农林路竹园小区21栋",
      "street": "香蜜湖街道竹园社区",
      "phone": 23600969,
      "organizer": "深圳市新竹教育投资有限公司",
      "legal_person": "韩素婷",
      "principal": "林燕青",
      "class": "区一级",
      "type": "民办非普惠园",
      "fee": 11800,
      "latitude": 22.538111,
      "longitude": 114.016345
  },
  {
      "number": 151,
      "name": "深圳市福田区银泰盈盈幼儿园",
      "created_time": "2002年04月",
      "address": "深圳市福田区福强路银泰苑3栋1D",
      "street": "福保街道福保社区",
      "phone": 82568776,
      "organizer": "孔夏",
      "legal_person": "孔夏",
      "principal": "孔夏",
      "class": "未评级",
      "type": "民办非普惠园",
      "fee": 7800,
      "latitude": 22.515901,
      "longitude": 114.064416
  },
  {
      "number": 152,
      "name": "深圳泰然幼儿园",
      "created_time": "2001年02月",
      "address": "福田区下沙泰然广场",
      "street": "沙头街道金碧社区",
      "phone": 23603965,
      "organizer": "深业泰然(集团）股份有限公司",
      "legal_person": "戴薇",
      "principal": "严欢欢",
      "class": "省一级",
      "type": "民办非普惠园",
      "fee": 4000,
      "latitude": 22.528093,
      "longitude": 114.024192
  },
  {
      "number": 153,
      "name": "深圳市福田区绿洲幼儿园",
      "created_time": "2000年12月",
      "address": "深圳市福田区福强路荔树人家小区一单元首层",
      "street": "沙头街道金地社区",
      "phone": 83841770,
      "organizer": "程莉",
      "legal_person": "刘程",
      "principal": "刘平",
      "class": "规范园",
      "type": "民办非普惠园",
      "fee": 1200,
      "latitude": 22.526535,
      "longitude": 114.033504
  },
  {
      "number": 154,
      "name": "深圳市福田区金色家园幼儿园",
      "created_time": "2003年03月",
      "address": "深圳市福田区莲花街道景田东路61号",
      "street": "莲花街道景田社区",
      "phone": 82549601,
      "organizer": "深圳帆盈教育发展有限公司",
      "legal_person": "叶婷",
      "principal": "陈丹",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 4176,
      "latitude": 22.555119,
      "longitude": 114.044457
  },
  {
      "number": 155,
      "name": "深圳卡通城幼儿园",
      "created_time": "1999年02月",
      "address": "深圳市福田区上梅林梅东一路4号",
      "street": "梅林街道翰岭社区",
      "phone": 83108484,
      "organizer": "马荣天使投资有限公司",
      "legal_person": "吴义生",
      "principal": "许凤鸣",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 3500,
      "latitude": 22.569982,
      "longitude": 114.067458
  },
  {
      "number": 156,
      "name": "深圳市福田区快乐宝贝幼儿园",
      "created_time": "2008年02月",
      "address": "深圳市福田区快乐宝贝幼儿园",
      "street": "莲花街道康欣社区",
      "phone": 83936969,
      "organizer": "深圳市恒玖润实业有限公司",
      "legal_person": "李学军",
      "principal": "刘燕",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 16800,
      "latitude": 22.552678,
      "longitude": 114.039108
  },
  {
      "number": 157,
      "name": "深圳市福田区金达来幼儿园",
      "created_time": "1999年09月",
      "address": "深圳市福田区滨河大道19栋3138号",
      "street": "福田街道圩镇社区",
      "phone": 83379671,
      "organizer": "李热军",
      "legal_person": "李热军",
      "principal": "谢礼敏",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 2600,
      "latitude": 22.531193,
      "longitude": 114.078526
  },
  {
      "number": 158,
      "name": "深圳市福田区童歌博尔幼儿园",
      "created_time": "2009年09月",
      "address": "深圳市福田区莲花街道景田南六街1号",
      "street": "莲花街道梅岭社区",
      "phone": 25311500,
      "organizer": "张媞",
      "legal_person": "张媞",
      "principal": "邢艳",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 6600,
      "latitude": 22.544767,
      "longitude": 114.042308
  },
  {
      "number": 159,
      "name": "深圳市福田区弗瑞德四季山水幼儿园",
      "created_time": "2011年07月",
      "address": "深圳市福田区上梅林龙尾路四季山水花园",
      "street": "梅林街道龙尾社区",
      "phone": 83298600,
      "organizer": "深圳市加州儿童会教育投资开发服务有限公司、吕辉",
      "legal_person": "张宇",
      "principal": "彭兰",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 12000,
      "latitude": 22.571537,
      "longitude": 114.044499
  },
  {
      "number": 160,
      "name": "深圳市福田区金生幼儿园有限公司",
      "created_time": "2020年07月",
      "address": "深圳市福田区莲花街道康欣社区景田北五街深圳市福田区金生幼儿园1层102",
      "street": "莲花街道康欣社区",
      "phone": 66666688,
      "organizer": "庄程翔",
      "legal_person": "庄程翔",
      "principal": "王雪凤",
      "class": "规范园",
      "type": "民办非普惠园",
      "fee": 22800,
      "latitude": 22.557541,
      "longitude": 114.035869
  },
  {
      "number": 161,
      "name": "深圳市福田区黄埔雅苑维育礼雅幼儿园有限公司",
      "created_time": "2021年02月",
      "address": "深圳市福田区福中路317号",
      "street": "莲花街道福新社区",
      "phone": 83282004,
      "organizer": "郭利民",
      "legal_person": "肖亮霞",
      "principal": "肖亮霞",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 18600,
      "latitude": 22.544143,
      "longitude": 114.052429
  },
  {
      "number": 162,
      "name": "深圳市福田区方方乐趣幼儿园",
      "created_time": "2007年04月",
      "address": "深圳市福田区金地海景花园金地十路21号",
      "street": "沙头街道翠湾社区",
      "phone": 23810830,
      "organizer": "深圳市瑞麟投资顾问有限公司",
      "legal_person": "杨峻中",
      "principal": "王亚月",
      "class": "规范园",
      "type": "民办非普惠园",
      "fee": 2400,
      "latitude": 22.517088,
      "longitude": 114.043076
  },
  {
      "number": 163,
      "name": "深圳市福田区维育礼雅幼儿园有限公司",
      "created_time": "2020年07月",
      "address": "深圳市福田区福强路2135号江南名苑AB栋一二层",
      "street": "沙头街道新洲社区",
      "phone": 82961010,
      "organizer": "深圳维育教育发展有限公司",
      "legal_person": "刘巧",
      "principal": "刘巧",
      "class": "区一级",
      "type": "民办非普惠园",
      "fee": 16800,
      "latitude": 22.515697,
      "longitude": 114.061539
  },
  {
      "number": 164,
      "name": "深圳市福田区贝赛思学校(幼儿园)",
      "created_time": "2020年08月",
      "address": "深圳市福田区新沙街2号",
      "street": "沙头街道新沙社区",
      "phone": 82887788,
      "organizer": "深圳)有限公司和深圳爱晖国际教育有限公司",
      "legal_person": "金东",
      "principal": "毛俪蓉",
      "class": "规范园",
      "type": "民办非普惠园",
      "fee": 24600,
      "latitude": 22.529277,
      "longitude": 114.047365
  },
  {
      "number": 165,
      "name": "深圳市福田区美懿英皇幼儿园有限公司",
      "created_time": "2020年09月",
      "address": "深圳市福田区香蜜湖街道农园路17号香榭里花园紫苑A、B栋1层裙楼",
      "street": "香蜜湖街道农园社区",
      "phone": 82722315,
      "organizer": "美懿教育（深圳）有限公司",
      "legal_person": "薛艳",
      "principal": "黄莉",
      "class": "省一级",
      "type": "民办非普惠园",
      "fee": 32800,
      "latitude": 22.542611,
      "longitude": 114.021304
  },
  {
      "number": 166,
      "name": "深圳市福田区科发幼儿园有限公司",
      "created_time": "2022年05月",
      "address": "深圳市福田区香蜜湖街道竹园社区农林路23号科发幼儿园",
      "street": "香蜜湖街道竹园社区",
      "phone": 82896866,
      "organizer": "深圳市蓝美佳承教育有限公司",
      "legal_person": "胥简雯",
      "principal": "徐晨",
      "class": "市一级",
      "type": "民办非普惠园",
      "fee": 24600,
      "latitude": 22.541343,
      "longitude": 114.013718
  },
  {
      "number": 167,
      "name": "深圳市福田区本一幼儿园有限公司",
      "created_time": "2022年10月",
      "address": "深圳市福田区梅林接到梅京社区莲塘尾二路7号兰江山第一期2栋B座3层整层",
      "street": "梅林街道梅京社区",
      "phone": 82533221,
      "organizer": "深圳市班尼香蜜教育咨询有限公司",
      "legal_person": "陈杰",
      "principal": "朱思涵",
      "class": "未评级",
      "type": "民办非普惠园",
      "fee": 22800,
      "latitude": 22.564374,
      "longitude": 114.014515
  },
  {
      "number": 168,
      "name": "深圳市福田区冠萃幼儿园有限公司",
      "created_time": "2022年11月",
      "address": "深圳市福田区香蜜湖街道香蜜社区香蜜湖路3012号熙园商场113号",
      "street": "香蜜湖街道香蜜社区",
      "phone": 23894487,
      "organizer": "深圳市冠萃教育文化有限公司",
      "legal_person": "杨清泽",
      "principal": "于亚萍",
      "class": "未评级",
      "type": "民办非普惠园",
      "fee": 17600,
      "latitude": 22.55107,
      "longitude": 114.022769
  },
  {
      "number": 169,
      "name": "深圳市福田区爱缔儿幼儿园有限公司",
      "created_time": "2023年4月",
      "address": "深圳市福田区安托山六路六号蔡屋围侨香雅居商住楼（综合楼1-25层）2、3层",
      "street": "香蜜湖街道香安社区",
      "phone": 23601446,
      "organizer": "深圳爱的堡教育科技有限公司",
      "legal_person": "陈奕彤",
      "principal": "王梦婷",
      "class": "未评级",
      "type": "民办非普惠园",
      "fee": 18800,
      "latitude": 22.546786,
      "longitude": 114.009203
  }
]

module.exports = {
  SCHOOLS: SCHOOLS
}